name: Build then Push to Registry

# Trigger on Github Release https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/managing-releases-in-a-repository
# Github release will create new git tag
# but git push origin --tag will not trigger this action
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially (with needs) or in parallel
jobs:
  # We use 2 jobs: continous-integrations and docker-build
  # docker-build will run after continous-integrations success

  continous-integrations:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Run your CI script before build docker image  
      - name: Build and Test
        run: # make install && \
             # make test && \
             # make coverage && \
             # make cleanup \
             echo "Simulate install, test and build"

